In [53]:
import numpy as np
x = np.random.randint(1,20,15)
print(x)


[ 1 11 17 12 13  4  7  6 19 14  1  1 13 14 19]


In [54]:
x=x.reshape(3,5)
print(x)

[[ 1 11 17 12 13]
 [ 4  7  6 19 14]
 [ 1  1 13 14 19]]


In [55]:
print(x.shape)

(3, 5)


In [56]:
a=x[0]
b=x[1]
c=x[2]
print(b)

[ 4  7  6 19 14]


In [57]:
a[a==a.max()]=0
b[b==b.max()]=0
c[c==c.max()]=0
print(x)

[[ 1 11  0 12 13]
 [ 4  7  6  0 14]
 [ 1  1 13 14  0]]


In [58]:
import pandas as pd
data=pd.read_csv("./data.csv")

print(data)




     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]


In [59]:
data.isnull().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

In [22]:
mean_value=data['Calories'].mean()
data

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [23]:
data['Calories'].fillna(value=mean_value,inplace=True)
data

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [24]:
data.isnull().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [60]:
data.agg({'Duration':['min','max','count','mean'],'Pulse':['min','max','count','mean']})

Duration       Pulse
min     15.000000   80.000000
max    300.000000  159.000000
count  169.000000  169.000000
mean    63.846154  107.461538

In [28]:
data[(data['Calories']>500) & (data['Calories']<1000)]


Duration  Pulse  Maxpulse  Calories
51         80    123       146     643.1
62        160    109       135     853.0
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
72         90    100       127     700.0
73        150     97       127     953.2
75         90     98       125     563.2
78        120    100       130     500.4
90        180    101       127     600.1
99         90     93       124     604.1
103        90     90       100     500.4
106       180     90       120     800.3
108        90     90       120     500.3

In [30]:
data[(data['Calories']>500) & (data['Pulse']<100)]


Duration  Pulse  Maxpulse  Calories
65        180     90       130     800.4
70        150     97       129    1115.0
73        150     97       127     953.2
75         90     98       125     563.2
99         90     93       124     604.1
103        90     90       100     500.4
106       180     90       120     800.3
108        90     90       120     500.3

In [33]:
df_modified=data.drop("Maxpulse",axis=1)
df_modified

Duration  Pulse  Calories
0          60    110     409.1
1          60    117     479.0
2          60    103     340.0
3          45    109     282.4
4          45    117     406.0
..        ...    ...       ...
164        60    105     290.8
165        60    110     300.0
166        60    115     310.2
167        75    120     320.4
168        75    125     330.4

[169 rows x 3 columns]

In [34]:
data=data.drop("Maxpulse",axis=1)
data

Duration  Pulse  Calories
0          60    110     409.1
1          60    117     479.0
2          60    103     340.0
3          45    109     282.4
4          45    117     406.0
..        ...    ...       ...
164        60    105     290.8
165        60    110     300.0
166        60    115     310.2
167        75    120     320.4
168        75    125     330.4

[169 rows x 3 columns]

In [36]:
data.Calories.dtype

dtype('float64')

In [38]:
data["Calories"] = data["Calories"].astype(float).astype(int)
data


Duration  Pulse  Calories
0          60    110       409
1          60    117       479
2          60    103       340
3          45    109       282
4          45    117       406
..        ...    ...       ...
164        60    105       290
165        60    110       300
166        60    115       310
167        75    120       320
168        75    125       330

[169 rows x 3 columns]

In [43]:
data.plot.scatter(x = 'Duration', y = 'Calories')


<AxesSubplot:xlabel='Duration', ylabel='Calories'>

In [44]:
python_df=pd.DataFrame({"popularity":[22.2, 17.6, 8.8, 8, 7.7, 6.7]},index=['Java','Python','PHP','JavaScript', 'C#', 'C++'])
python_df

popularity
Java              22.2
Python            17.6
PHP                8.8
JavaScript         8.0
C#                 7.7
C++                6.7

In [45]:
myexplode = [0.2, 0, 0, 0,0,0]
python_df.plot.pie(subplots=True,autopct='%1.1f%%',explode=myexplode,figsize=[10,10],startangle=140,shadow=True)

array([<AxesSubplot:ylabel='popularity'>], dtype=object)